import { useMemo, useState } from 'react'
import Icon from './Icon'

const steps = ['Appliance & Problem', 'Service Location', 'Preferred Appointment', 'Contact Information', 'Review & Submit']
const appliances = ['Refrigerator/Freezer', 'Washer/Dryer', 'Dishwasher', 'Oven/Range', 'Air Conditioner/HVAC', 'Other']
const problems = ['Not cooling or heating', 'Not starting or powering on', 'Leaking or draining issue', 'Unusual noise or vibration', 'Error code or display issue', 'Other']
const timeWindows = ['Morning (8 AM – 12 PM)', 'Afternoon (12 PM – 4 PM)', 'Evening (4 PM – 7 PM)']

const blankForm = { appliance: '', problem: '', problemOther: '', details: '', zip: '', address: '', city: '', state: '', date: '', time: '', firstName: '', lastName: '', email: '', phone: '', contact: 'Phone' }
const label = 'block text-sm font-semibold text-[#001428]'
const input = 'mt-1.5 w-full rounded-lg border border-[#c3c6ce] bg-white px-3 py-2.5 text-sm text-[#0d1c2f] outline-none transition focus:border-[#0051d5] focus:ring-4 focus:ring-[#0051d5]/15'

function today() { return new Date().toISOString().slice(0, 10) }
function Summary({ title, children, onEdit }) { return <section className="rounded-xl border border-[#dde9ff] bg-white p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-heading text-base font-bold text-[#001428]">{title}</h3><button type="button" className="text-sm font-bold text-[#0051d5] hover:underline" onClick={onEdit}>Edit</button></div><div className="mt-3 grid gap-2 text-sm text-[#43474d] sm:grid-cols-2">{children}</div></section> }
function Detail({ name, value }) { return <p><span className="font-semibold text-[#001428]">{name}:</span> {value || '—'}</p> }

export default function BookingFlow({ initialData, onExit }) {
  const [step, setStep] = useState(0)
  const [form, setForm] = useState(() => ({ ...blankForm, ...initialData }))
  const [errors, setErrors] = useState({})
  const [reference, setReference] = useState('')
  const minDate = useMemo(today, [])
  const update = (field, value) => setForm(current => ({ ...current, [field]: value }))

  function validate(currentStep) {
    const next = {}
    if (currentStep === 0) { if (!form.appliance) next.appliance = 'Choose an appliance type.'; if (!form.problem) next.problem = 'Choose a general problem.'; if (form.problem === 'Other' && !form.problemOther.trim()) next.problemOther = 'Describe the general problem.' }
    if (currentStep === 1) { if (!/^\d{5}$/.test(form.zip)) next.zip = 'Enter a valid 5-digit ZIP code.'; if (!form.address.trim()) next.address = 'Enter a street address.'; if (!form.city.trim()) next.city = 'Enter a city.'; if (!/^[A-Za-z]{2}$/.test(form.state)) next.state = 'Enter a two-letter state abbreviation.' }
    if (currentStep === 2) { if (!form.date) next.date = 'Choose a preferred date.'; if (form.date && form.date < minDate) next.date = 'Choose today or a future date.'; if (!form.time) next.time = 'Choose a preferred time window.' }
    if (currentStep === 3) { if (!form.firstName.trim()) next.firstName = 'Enter your first name.'; if (!form.lastName.trim()) next.lastName = 'Enter your last name.'; if (!/^\S+@\S+\.\S+$/.test(form.email)) next.email = 'Enter a valid email address.'; if (!/^[\d\s()+-]{7,}$/.test(form.phone)) next.phone = 'Enter a valid phone number.'; if (!form.contact) next.contact = 'Choose a contact method.' }
    setErrors(next)
    return Object.keys(next).length === 0
  }
  function next() { if (validate(step)) { setErrors({}); setStep(value => value + 1); window.scrollTo({ top: 0, behavior: 'smooth' }) } }
  function back() { setErrors({}); setStep(value => Math.max(0, value - 1)); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  function submit() { if (!validate(3)) return setStep(3); setReference(`FP-DEMO-${Date.now().toString(36).toUpperCase()}`) }
  if (reference) return <main id="main-content" className="booking-page"><div className="booking-shell text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#e6eeff] text-[#0051d5]"><Icon className="text-[30px]">check_circle</Icon></div><p className="eyebrow mt-5">Demo request received</p><h1 className="section-title text-3xl">Your demo request is ready for review.</h1><p className="mx-auto mt-3 max-w-xl text-base leading-6 text-[#43474d]">This is a portfolio demo. No appointment has been booked, no information has been sent, and no personal information has been stored.</p><div className="mx-auto mt-6 max-w-md rounded-xl border border-[#bfdbfe] bg-[#eff6ff] p-4 text-left"><p className="text-xs font-bold uppercase tracking-wider text-[#0051d5]">Demo reference number</p><p className="mt-1 font-heading text-xl font-bold text-[#001428]">{reference}</p><p className="mt-2 text-sm text-[#43474d]">In a production version, this screen could hand off a request to a service team. This demonstration does not do so.</p></div><button className="button button-blue mt-7 h-12 px-6" onClick={onExit}><Icon>home</Icon>Return to Home</button></div></main>

  return <main id="main-content" className="booking-page"><div className="booking-shell"><div className="mb-7 flex items-center justify-between gap-4"><button type="button" className="inline-flex items-center gap-1 text-sm font-bold text-[#0051d5] hover:underline" onClick={onExit}><Icon className="text-[18px]">arrow_back</Icon>Back to site</button><span className="text-xs font-semibold text-[#43474d]">Client-side demo only</span></div><header className="mb-7"><p className="eyebrow">Booking Demonstration</p><h1 className="section-title">Explore Booking Demo</h1><p className="section-copy max-w-2xl">Tell us about your appliance and preferred time. This form creates a demo request only—it does not book an appointment.</p></header><ol className="mb-8 grid grid-cols-5 gap-1" aria-label="Booking progress">{steps.map((name, index) => <li key={name} className="min-w-0"><div className={`h-1 rounded-full ${index <= step ? 'bg-[#0051d5]' : 'bg-[#d5e3fd]'}`}/><span className={`mt-2 block text-center text-[10px] font-semibold sm:text-xs ${index === step ? 'text-[#0051d5]' : 'text-[#74777e]'}`} aria-current={index === step ? 'step' : undefined}>{index + 1}. <span className="hidden md:inline">{name}</span></span></li>)}</ol><div className="rounded-2xl border border-[#dde9ff] bg-white p-5 shadow-[0_4px_16px_rgba(15,41,66,.06)] sm:p-7"><p className="text-xs font-bold uppercase tracking-wider text-[#0051d5]">Step {step + 1} of 5</p><h2 className="mt-1 font-heading text-2xl font-bold tracking-tight text-[#001428]">{steps[step]}</h2>{Object.keys(errors).length > 0 && <div className="mt-4 rounded-lg border border-[#ffdad6] bg-[#fff6f5] p-3 text-sm text-[#93000a]" role="alert">Please correct the highlighted fields before continuing.</div>}
        {step === 0 && <div className="mt-6 grid gap-5"><div><label className={label} htmlFor="appliance">Appliance type</label><select id="appliance" className={input} value={form.appliance} onChange={e => update('appliance', e.target.value)}><option value="">Select appliance type</option>{appliances.map(item => <option key={item}>{item}</option>)}</select>{errors.appliance && <p className="field-error">{errors.appliance}</p>}</div><div><label className={label} htmlFor="problem">General problem</label><select id="problem" className={input} value={form.problem} onChange={e => update('problem', e.target.value)}><option value="">Select a general problem</option>{problems.map(item => <option key={item}>{item}</option>)}</select>{errors.problem && <p className="field-error">{errors.problem}</p>}</div>{form.problem === 'Other' && <div><label className={label} htmlFor="problem-other">Describe the general problem</label><input id="problem-other" className={input} value={form.problemOther} onChange={e => update('problemOther', e.target.value)} />{errors.problemOther && <p className="field-error">{errors.problemOther}</p>}</div>}<div><label className={label} htmlFor="details">Tell us more about the problem <span className="font-normal text-[#74777e]">(optional)</span></label><textarea id="details" rows="4" className={input} value={form.details} onChange={e => update('details', e.target.value)} /></div></div>}
        {step === 1 && <div className="mt-6 grid gap-5 sm:grid-cols-2"><div><label className={label} htmlFor="zip">ZIP code</label><input id="zip" className={input} inputMode="numeric" maxLength="5" value={form.zip} onChange={e => update('zip', e.target.value.replace(/\D/g, '').slice(0, 5))} />{errors.zip && <p className="field-error">{errors.zip}</p>}</div><div className="sm:col-span-2"><label className={label} htmlFor="address">Street address</label><input id="address" className={input} autoComplete="street-address" value={form.address} onChange={e => update('address', e.target.value)} />{errors.address && <p className="field-error">{errors.address}</p>}</div><div><label className={label} htmlFor="city">City</label><input id="city" className={input} autoComplete="address-level2" value={form.city} onChange={e => update('city', e.target.value)} />{errors.city && <p className="field-error">{errors.city}</p>}</div><div><label className={label} htmlFor="state">State</label><input id="state" className={input} autoComplete="address-level1" maxLength="2" placeholder="TX" value={form.state} onChange={e => update('state', e.target.value.toUpperCase().replace(/[^A-Z]/g, ''))} />{errors.state && <p className="field-error">{errors.state}</p>}</div></div>}
        {step === 2 && <div className="mt-6 grid gap-5"><div><label className={label} htmlFor="date">Preferred date</label><input id="date" type="date" min={minDate} className={input} value={form.date} onChange={e => update('date', e.target.value)} />{errors.date && <p className="field-error">{errors.date}</p>}</div><fieldset><legend className={label}>Preferred time window</legend><p className="mt-1 text-sm text-[#43474d]">These are preferred times only and do not show real-time availability.</p><div className="mt-3 grid gap-2 sm:grid-cols-3">{timeWindows.map(option => <label key={option} className={`cursor-pointer rounded-xl border p-3 text-sm font-semibold ${form.time === option ? 'border-[#0051d5] bg-[#eff6ff] text-[#001d35]' : 'border-[#dde9ff] text-[#43474d]'}`}><input className="sr-only" type="radio" name="time" value={option} checked={form.time === option} onChange={e => update('time', e.target.value)} />{option}</label>)}</div>{errors.time && <p className="field-error">{errors.time}</p>}</fieldset></div>}
        {step === 3 && <div className="mt-6 grid gap-5 sm:grid-cols-2"><div><label className={label} htmlFor="first-name">First name</label><input id="first-name" className={input} autoComplete="given-name" value={form.firstName} onChange={e => update('firstName', e.target.value)} />{errors.firstName && <p className="field-error">{errors.firstName}</p>}</div><div><label className={label} htmlFor="last-name">Last name</label><input id="last-name" className={input} autoComplete="family-name" value={form.lastName} onChange={e => update('lastName', e.target.value)} />{errors.lastName && <p className="field-error">{errors.lastName}</p>}</div><div className="sm:col-span-2"><label className={label} htmlFor="email">Email</label><input id="email" type="email" className={input} autoComplete="email" value={form.email} onChange={e => update('email', e.target.value)} />{errors.email && <p className="field-error">{errors.email}</p>}</div><div><label className={label} htmlFor="phone">Phone number</label><input id="phone" type="tel" className={input} autoComplete="tel" value={form.phone} onChange={e => update('phone', e.target.value)} />{errors.phone && <p className="field-error">{errors.phone}</p>}</div><div><label className={label} htmlFor="contact">Preferred contact method</label><select id="contact" className={input} value={form.contact} onChange={e => update('contact', e.target.value)}><option>Phone</option><option>Email</option></select>{errors.contact && <p className="field-error">{errors.contact}</p>}</div></div>}
        {step === 4 && <div className="mt-6 space-y-3"><Summary title="Appliance & Problem" onEdit={() => setStep(0)}><Detail name="Appliance" value={form.appliance}/><Detail name="Problem" value={form.problem === 'Other' ? form.problemOther : form.problem}/>{form.details && <Detail name="Details" value={form.details}/>}</Summary><Summary title="Service Location" onEdit={() => setStep(1)}><Detail name="Address" value={form.address}/><Detail name="Location" value={`${form.city}, ${form.state} ${form.zip}`}/></Summary><Summary title="Preferred Appointment" onEdit={() => setStep(2)}><Detail name="Date" value={form.date}/><Detail name="Time" value={form.time}/><p className="sm:col-span-2 text-xs">Preferred time only; this is not real-time availability.</p></Summary><Summary title="Contact Information" onEdit={() => setStep(3)}><Detail name="Name" value={`${form.firstName} ${form.lastName}`}/><Detail name="Email" value={form.email}/><Detail name="Phone" value={form.phone}/><Detail name="Contact method" value={form.contact}/></Summary><p className="rounded-lg bg-[#eff4ff] p-3 text-sm text-[#43474d]"><strong className="text-[#001428]">Demo notice:</strong> submitting will generate a demo reference number only. No appointment will be booked or data sent.</p></div>}
        <div className="mt-8 flex items-center justify-between gap-3 border-t border-[#eff4ff] pt-5">{step > 0 ? <button type="button" className="button h-11 border border-[#c3c6ce] bg-white px-5 text-[#001428] hover:bg-[#eff4ff]" onClick={back}><Icon>arrow_back</Icon>Back</button> : <span/>}{step < 4 ? <button type="button" className="button button-blue h-11 px-5" onClick={next}>Continue<Icon>arrow_forward</Icon></button> : <button type="button" className="button button-blue h-11 px-5" onClick={submit}>Submit Service Request<Icon>send</Icon></button>}</div>
      </div></div></main>
}
