import Icon from './Icon'

const pages = {
  privacy: { eyebrow: 'Portfolio Demo Privacy Policy', title: 'Privacy Policy', sections: [['No data collection', 'This fictional portfolio demonstration does not submit, transmit, retain, or store information entered into the booking form.'], ['Local interaction only', 'Form fields and the demo reference number exist only in the active browser session to demonstrate interface behavior.'], ['No service relationship', 'Using this website does not create a customer relationship, request service, or contact FixPro Home Services.']] },
  terms: { eyebrow: 'Portfolio Demo Terms of Use', title: 'Terms of Use', sections: [['Demonstration purpose', 'FixPro Home Services is a fictional business concept presented for portfolio and interface demonstration purposes only.'], ['Illustrative content', 'Service categories, locations, imagery, booking steps, and supporting copy are illustrative and are not an offer to provide repair services.'], ['No reliance', 'Do not rely on this website for scheduling, pricing, availability, professional advice, or real-world service information.']] },
  disclaimer: { eyebrow: 'Portfolio Demo Disclaimer', title: 'Demo Disclaimer', sections: [['Fictional business', 'FixPro Home Services is not a real operating business. Its branding, operational claims, sample testimonials, service areas, and booking flow are fictional portfolio content.'], ['Sample testimonials', 'All testimonial-style cards are clearly labeled samples. They do not represent real customers, ratings, reviews, or service outcomes.'], ['No appointment confirmation', 'The booking flow produces a demo reference only. It never creates a real appointment, sends an email, contacts a technician, or stores personal information.']] }
}

export default function LegalPage({ page, onExit }) {
  const content = pages[page]
  return <main id="main-content" className="booking-page"><article className="booking-shell"><button type="button" className="inline-flex items-center gap-1 text-sm font-bold text-[#0051d5] hover:underline" onClick={onExit}><Icon className="text-[18px]">arrow_back</Icon>Back to site</button><p className="eyebrow mt-7">{content.eyebrow}</p><h1 className="section-title">{content.title}</h1><p className="section-copy mt-3">This page applies only to this fictional portfolio demonstration.</p><div className="mt-7 space-y-4">{content.sections.map(([title, body]) => <section key={title} className="rounded-xl border border-[#dde9ff] bg-white p-5 shadow-sm"><h2 className="font-heading text-lg font-bold text-[#001428]">{title}</h2><p className="mt-2 text-sm leading-6 text-[#43474d]">{body}</p></section>)}</div></article></main>
}
